jenkinsci/jira-plugin

- src/main/java/hudson/plugins/jira/JiraMailAddressResolver.java
- src/test/java/hudson/plugins/jira/MailResolverTest.java
Setting the system property `-Dhudson.plugins.jira.JiraMailAddressResolver.DISABLE=true` will disable resolving email addresses with Jira.
The reason for disabling the JiraMailAddressResolver is because it will access Jira to obtain the email address which could potentially return an invalid email (as in `JENKINS-23292`). Disabling the email resolver for Jira will allow the email addresses to be resolved through another method (possibly with `LDAP`).
> [JENKINS-23292] Add system property to disable jira mail address resolving

- src/main/java/hudson/plugins/jira/JiraIssueUpdateBuilder.java
Like the jql and comment, the workflowActionName is now expanded and
resolved against build parameters when performing the
JiraIssueUpdateBuilder
> Add ability to expand workflowActionName

- src/main/java/hudson/plugins/jira/JiraRestService.java
- src/test/java/hudson/plugins/jira/JiraRestServiceTest.java
Take into account the base path of JIRA site URL when building URIs for REST API calls.
Fixes: JENKINS-30408
> [JENKINS-30408] Fixed URI composition for REST API calls

- src/main/java/hudson/plugins/jira/versionparameter/CompRemoteVersion.java
- src/main/java/hudson/plugins/jira/versionparameter/JiraVersionParameterDefinition.java
In relation with [this issue] (https://issues.jenkins-ci.org/browse/JENKINS-26701), I have ordered versions  on Build with Parameters in funcion of the name.
> Versions Sorted in Jira Release Version Parameter

- src/main/java/hudson/plugins/jira/DefaultUpdaterIssueSelector.java
- src/main/java/hudson/plugins/jira/JiraIssueUpdater.java
- src/main/java/hudson/plugins/jira/Updater.java
- src/main/java/hudson/plugins/jira/UpdaterIssueSelector.java
- src/main/resources/hudson/plugins/jira/DefaultUpdaterIssueSelector/config.jelly
- src/main/resources/hudson/plugins/jira/JiraIssueUpdater/config.jelly
- src/main/resources/hudson/plugins/jira/Messages.properties
- src/test/java/hudson/plugins/jira/JiraIssueUpdaterTest.java
This sort of fixes [JENKINS-1691](https://issues.jenkins-ci.org/browse/JENKINS-1691) and [JENKINS-25014](https://issues.jenkins-ci.org/browse/JENKINS-25014) - it will require other plugins (probably custom ones) to provide issue selectors to get the demanded behavior.
> Pluggable strategy of selecting which issues are relevant to update

- src/main/java/hudson/plugins/jira/Updater.java
Fix ugly comment message if there are *multiple changesets*. All changesets joined into one *ul* list which looks strange. They should be placed in each paragraph separately.
> Split each SCM changes in paragraphs

- pom.xml
- src/main/java/hudson/plugins/jira/versionparameter/VersionComparator.java
- src/test/java/hudson/plugins/jira/versionparameter/VersionComparatorTest.groovy
use Maven ComparableVersion to support release candidates (RCs) in version numbers, currently these version are not shown in JiraVersionParameterDefinition
> use Maven ComparableVersion to support RC in version number

- src/main/java/hudson/plugins/jira/JiraVersionCreator.java
- src/main/resources/hudson/plugins/jira/Messages.properties
- src/test/java/hudson/plugins/jira/JiraVersionCreatorTest.java
Similar to #77 - use resource bundle instead of string constant, also print a message on success
> console message improvement for JiraVersionCreator

- COMPATIBILITY.md
- pom.xml
- src/main/java/hudson/plugins/jira/DefaultUpdaterIssueSelector.java
- src/main/java/hudson/plugins/jira/JiraChangeLogAnnotator.java
- src/main/java/hudson/plugins/jira/JiraIssueUpdater.java
- src/main/java/hudson/plugins/jira/JiraRestService.java
- src/main/java/hudson/plugins/jira/JiraSession.java
- src/main/java/hudson/plugins/jira/JiraSite.java
- src/main/java/hudson/plugins/jira/Updater.java
- src/main/java/hudson/plugins/jira/listissuesparameter/JiraIssueParameterDefinition.java
- src/main/java/hudson/plugins/jira/versionparameter/JiraVersionParameterDefinition.java
- src/main/resources/hudson/plugins/jira/JiraSite/config.jelly
- src/main/resources/hudson/plugins/jira/JiraSite/config.properties
- src/main/resources/hudson/plugins/jira/JiraSite/help-timeout.html
- src/test/java/JiraTester.java
- src/test/java/hudson/plugins/jira/DescriptorImplTest.java
- src/test/java/hudson/plugins/jira/JiraBuildActionTest.java
- src/test/java/hudson/plugins/jira/JiraChangeLogAnnotatorTest.java
- src/test/java/hudson/plugins/jira/JiraIssueUpdaterTest.java
- src/test/java/hudson/plugins/jira/JiraRestServiceTest.java
- src/test/java/hudson/plugins/jira/UpdaterTest.java
- src/test/java/hudson/plugins/jira/deprecated/DeprecatedJiraBuildAction.java
+ I fixed "JIRA Release Version Parameter" and "JIRA Issue Parameter" - they can be used with workflow jobs now. 
+ I repair JiraChangeLogAnnotator - it automatically work now with workflow projects. 
+ Finally i change Updater, so JJiraIssueUpdater can be used in workflow script. I used it in our build like this:
```
def scm = [$class: 'GitSCM', .... 
checkout poll: false, scm: scm
step([$class: 'hudson.plugins.jira.JiraIssueUpdater', 
issueSelector: [$class: 'hudson.plugins.jira.DefaultUpdaterIssueSelector'], scm: scm]).
```
+ i add support for adding label to jira issue with JiraIssueUpdater, because we need it in out development workflow
+ i added option to change rest api timeout, becasuse our testing jira site is very slow ;) (JENKINS-31113)
[<img …
> JENKINS-28946 - JIRA support for Workflow jobs

- src/main/java/hudson/plugins/jira/JiraEnvironmentContributingAction.java
- src/main/java/hudson/plugins/jira/JiraEnvironmentVariableBuilder.java
- src/main/resources/hudson/plugins/jira/JiraEnvironmentVariableBuilder/config.jelly
- src/main/resources/hudson/plugins/jira/JiraEnvironmentVariableBuilder/help.html
- src/main/resources/hudson/plugins/jira/Messages.properties
- src/test/java/hudson/plugins/jira/JiraEnvironmentContributingActionTest.java
- src/test/java/hudson/plugins/jira/JiraEnvironmentVariableBuilderTest.java
This is a new build step that adds JIRA info to the build environment variables.  
The main use case is to add this to the build, then use the resulting JIRA_ISSUES variable (extracted from the commit log) in the JQL selector for "Progress JIRA issues by workflow action" or "Move issues matching JQL to the specified version".  This supports an automated workflow where issues get picked up and modified automatically by being referenced in the commit log.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/jenkinsci/jira-plugin/79)
> Add JiraEnvironmentVariableBuilder

- src/main/java/hudson/plugins/jira/JiraSite.java
- src/main/java/hudson/plugins/jira/Updater.java
- src/main/resources/hudson/plugins/jira/JiraSite/config.jelly
- src/main/resources/hudson/plugins/jira/JiraSite/help-appendChangeTimestamp.html
- src/main/resources/hudson/plugins/jira/JiraSite/help-dateTimePattern.html
- src/test/java/hudson/plugins/jira/MockAffectedFile.java
- src/test/java/hudson/plugins/jira/UpdaterTest.java
it's nice to have date and time of scm entries along with their author and id in comment messages.
It was proved by daily practice in our company. 
+ I refactor creation of one scm entry change description into method createScmChangeEntryDescription to be able to test it.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/jenkinsci/jira-plugin/83)
> Add SCM timestamp to JIRA comments

- src/main/java/hudson/plugins/jira/versionparameter/JiraVersionParameterValue.java
Calling `JiraVersionParameterValue.buildEnvironment()` would invariably cause `NullPointerException` since parent's `getValue()` implementation always returns `null`.
It appears that commit 73bdc422c16d4b61280feb9370e3f38ee1451c01 rewrote `buildEnvironment()` not considering the actual value provided by `getVersion()`, as initial implementation did (see commit 101065bd8ef07bd2f45532bc801ba7509fe35383).
This should solve [JENKINS-33211](https://issues.jenkins-ci.org/browse/JENKINS-33211).
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/jenkinsci/jira-plugin/90)
> [JENKINS-33211] jira-plugin: fixed environment building

- src/main/java/hudson/plugins/jira/JiraSite.java
If you try to add and empty jira plugin configuration at Manage Jenkins, will fail with NPE.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jenkinsci/jira-plugin/100)
> JENKINS-33166 check for nonnull url inside constructor

- src/main/java/hudson/plugins/jira/JiraSession.java
- src/main/resources/hudson/plugins/jira/JiraIssueMigrator/help-jiraReplaceVersion.html
- src/test/java/hudson/plugins/jira/JiraReplaceFixVersionByRegExTest.java
Wanting to remove all Versions on an issue based on a regular expression, e.g. "*-SNAPSHOT"
Use Case: Having automated deployments to a test environment, continuously wanting to update the tickets version to the latest snapshot-deployment until QA has confirmed the ticket or if it comes back from QA and gets deployed again. 
This way, only the latest snapshot-version is in the fixVersion list, not affecting the targeted release-version (e.g. "2.5.8-final") next to it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jenkinsci/jira-plugin/103)
> JiraSession.java - "Replace Jira Release" as RegEx

- src/main/java/hudson/plugins/jira/JiraRestService.java
Hello,
I think that stacktrace are missing to understand some issues.
This patch adds a stacktrace to each log of level warn.
Regards.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jenkinsci/jira-plugin/105)
> Add stack trace to warning logs generated by JiraRestService

- src/main/java/hudson/plugins/jira/JiraIssueField.java
- src/main/java/hudson/plugins/jira/JiraIssueFieldUpdater.java
- src/main/java/hudson/plugins/jira/JiraRestService.java
- src/main/java/hudson/plugins/jira/JiraSession.java
- src/main/resources/hudson/plugins/jira/JiraIssueFieldUpdater/config.jelly
- src/main/resources/hudson/plugins/jira/JiraIssueFieldUpdater/help-field_id.html
- src/main/resources/hudson/plugins/jira/JiraIssueFieldUpdater/help.html
- src/main/resources/hudson/plugins/jira/Messages.properties
- src/test/java/hudson/plugins/jira/JiraIssueFieldUpdaterTest.java
Add JiraIssueFieldUpdater class for update issue custom field, 
Class is support Jenkins Pipeline Plugin. Pipeline example:
step([$class: 'JiraIssueFieldUpdater', field_id: '10100', field_value: '#1020', issueSelector: [$class: 'ExplicitIssueSelector', issueKeys: 'PI-11, PI-12, PI-13']])
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jenkinsci/jira-plugin/104)
> Add support for updating JIRA Custom Fields

- src/main/java/hudson/plugins/jira/JiraBuildAction.java
- src/main/java/hudson/plugins/jira/JiraCarryOverAction.java
- src/main/java/hudson/plugins/jira/JiraChangeLogAnnotator.java
- src/main/java/hudson/plugins/jira/JiraSite.java
- src/main/java/hudson/plugins/jira/Updater.java
- src/main/java/hudson/plugins/jira/model/JiraIssue.java
- src/main/resources/hudson/plugins/jira/JiraBuildAction/summary.jelly
- src/test/java/hudson/plugins/jira/UpdaterTest.java
- src/test/java/hudson/plugins/jira/deprecated/DeprecatedJiraBuildAction.java
This change makes it possible to access JIRA actions through the REST API
GET /blue/rest/organizations/jenkins/pipelines/testing/branches/master/runs/2/jira/
```
{
"_class": "hudson.plugins.jira.JiraBuildAction",
"issues": [
{
"key": "JENKINS-38522",
"summary": "Long stage names overflow poorly on stage graph"
},
{
"key": "JENKINS-37295",
"summary": "Redesign the empty states"
}
],
"serverURL": "https://issues.jenkins-ci.org/"
}
```
Here's whats possible https://github.com/i386/blueocean-jira-plugin
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jenkinsci/jira-plugin/108)
> Export the JIRA action so that we can use it from Blue Ocean's REST API

- src/main/java/hudson/plugins/jira/JiraCreateIssueNotifier.java
- src/main/java/hudson/plugins/jira/JiraRestService.java
- src/main/java/hudson/plugins/jira/JiraSession.java
- src/main/resources/hudson/plugins/jira/JiraCreateIssueNotifier/config.jelly
- src/main/resources/hudson/plugins/jira/JiraCreateIssueNotifier/help-actionIdOnSuccess.html
- src/main/resources/hudson/plugins/jira/JiraCreateIssueNotifier/help-priorityId.html
- src/main/resources/hudson/plugins/jira/JiraCreateIssueNotifier/help-typeId.html
- src/test/java/hudson/plugins/jira/JiraCreateIssueNotifierTest.java
Motivation:
When Jenkins creates a JIRA ticket the priority and type ids are hardcoded and may break ticket creation as noted in JENKINS-31164.
Modifications:
Allow the admin to configure issue priority id and type id from the Jenkins job configuration.
Allow the admin to configure actionId on success which allows the plugin to automatically resolve or close tickets.
Result:
Support for JIRA where the type ids are different and greater flexibility when setting up workflows.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jenkinsci/jira-plugin/112)
> JENKINS-31164: Configurable issue priority, type and actionIdOnSuccess.

- pom.xml
- src/main/java/hudson/plugins/jira/JiraBuildAction.java
- src/main/java/hudson/plugins/jira/JiraChangeLogAnnotator.java
- src/main/java/hudson/plugins/jira/JiraJobAction.java
- src/main/java/hudson/plugins/jira/JiraSite.java
- src/test/java/hudson/plugins/jira/JiraJobActionTest.java
Add JiraJobAction to store a reference a JIRAIssue if a MultibranchPipeline has a branch with a issue key in its name.
It is a common pattern to include a JIRA ticket reference in a branch name like `feature/JENKINS-1234`
This action will allow us to link to it like this:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jenkinsci/jira-plugin/114)
> Add support for parsing branch names containing JIRA IDs

- src/main/java/hudson/plugins/jira/JiraChangeLogAnnotator.java
If we are unable to locate a remote issue, we get a very large stack trace about it. It already reports under `getIssue` that the issue does not exist. Setting the level to `FINE` for the stack trace only should reduce the amount of noise about not properly being able to locate the jira issue.
@reviewbybees 
```
Feb 27, 2017 5:15:47 AM hudson.plugins.jira.JiraChangeLogAnnotator annotate
INFO: Annotating JIRA id: 'SMPL-1234'
Feb 27, 2017 5:15:47 AM hudson.plugins.jira.JiraRestService getIssue
WARNING: jira rest client get issue error. cause: RestClientException{statusCode=Optional.of(404), errorCollections=[ErrorCollection{status=404, errors={}, errorMessages=[Issue Does Not Exist]}]}
Feb 27, 2017 5:15:47 AM hudson.plugins.jira.JiraChangeLogAnnotator annotate
WARNING: Error getting remote …
```
> Set log level to FINE if we can't find the remote issue

- src/main/resources/hudson/plugins/jira/JiraVersionCreatorBuilder/config.jelly
- src/main/resources/hudson/plugins/jira/JiraVersionCreatorBuilder/help-jiraProjectKey.html
- src/main/resources/hudson/plugins/jira/JiraVersionCreatorBuilder/help-jiraVersion.html
copy JiraVersionCreator resources to new dir JiraVersionCreatorBuilder.  Resolves open (unconfirmed) bug reported here: https://issues.jenkins-ci.org/browse/JENKINS-40571
this will allow users to enter the required parameters for the 'JIRA: Create new version' build step, which is not currently visible in 2.3 because of the lack of the resources directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jenkinsci/jira-plugin/122)
> JENKINS-40571 - JiraVersionCreatorBuilder fields missing in post-build form

- pom.xml
In this change:
* Upgrade the JIRA client to 4.0.0 
* Remove dependency on `jira-rest-java-client-plugin`. This module is a Atlassian plugin and only makes sense to be deployed within a JVM running the Atlassian plugin system.
PTAL @warden 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jenkinsci/jira-plugin/125)
> Upgrade JIRA client to 4.0.0 and remove unneeded dependency on plugin

- pom.xml
* Jackson is a lot older than what is used in most Jenkins plugins
* httpcomponents is also a lot loder than what is used elsewhere
** Let maven figure out the right version of `httpcore`
* Branch API 2.0
* Mailer and matrix have had security releases
* Update to latest of misc test libraries used
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jenkinsci/jira-plugin/126)
> Use modern dependencies

- src/main/java/hudson/plugins/jira/JiraJobAction.java
- src/main/java/hudson/plugins/jira/JiraSite.java
- src/test/java/hudson/plugins/jira/JiraJobActionTest.java
Pipeline will URL encode job names if the branch or PR name contains a '/' or other non-URL safe characters.
For example a branch will be called "feature/EXAMPLE-123" but the job name would be encoded as "feature%2FEXAMPLE-123". 
In this scenario the search for the JIRA issue key would fail and the action would not be set.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jenkinsci/jira-plugin/127)
> JiraJobAction is not set for job names that are URL encoded

- pom.xml
The certificate for m2proxy.atlassian.com has expired today, and the best I can tell is that the domain is deprecated in favor of maven.atlassian.com
> Switch to a more up-to-date domain name for Atlassian deps

- pom.xml
We were bringing in httpclient-cache 4.4.1 when this version should have matched httpclient 4.5.3.
On further inspection, the Atlassian dependencies are bringing in all sorts of interesting dependencies on HTTP Components that we don't need.
> JENKINS-48357 Older version of httpclient-cache causing IllegalAccessError

- pom.xml
I was experimenting with Jackson replacement by Jackson2 API Plugin.
It didn't fly well due to the 2.60.x requirement in that plugin, but I have at least bumped the version and added TODO.
* Changelog: https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.8.10
* Full diff: https://github.com/FasterXML/jackson-databind/compare/jackson-databind-2.8.9...jackson-databind-2.8.10
@reviewbybees
> Update Jackson components to 2.8.10

- src/main/java/hudson/plugins/jira/JiraSite.java
- src/test/groovy/hudson/plugins/jira/JiraSiteTest.groovy
Issue link [JENKINS-48716](https://issues.jenkins-ci.org/browse/JENKINS-48716)
> JENKINS-48716 Prevent Guava InvalidCacheLoadException

- pom.xml
- src/main/java/hudson/plugins/jira/JiraSite.java
- src/test/java/hudson/plugins/jira/JiraSite2Test.java
My bad, I didn't pay attention to this during the code review. The client should nit be excluded in such way. The right approach would be to ban imports in Maven Enforcer plugin.
@reviewbybees @i386 @warden
> Revert the bogus Atlassian HttpClient exclusion from #133

- src/main/java/hudson/plugins/jira/JiraIssueUpdater.java
- src/test/java/hudson/plugins/jira/JiraIssueUpdaterTest.java
After updating my jenkins and jira plugin versions, when creating an instance of JiraIssueUpdater inside my pipeline code I encountered https://issues.jenkins-ci.org/browse/JENKINS-45933
Example code that produces the issue:
`step([$class: 'hudson.plugins.jira.JiraIssueUpdater',
issueSelector: [$class: 'hudson.plugins.jira.selector.ExplicitIssueSelector', issueKeys: jiraTicket],
scm: [$class: 'GitSCM',
branches: [[name: issueBranch]],
userRemoteConfigs: [[url: 'ssh://git@source.git', credentialsId: 'user']],
extensions: []],
labels: null])`
From what I can tell this issue arises because instead of using the provided constructor the pipeline code instead tries to use the no arg constructor and then use setters to modify the object state. I could be wrong but I think it's the change in …
> JENKINS-45933 fix warning messages when creating a JiraIssueUpdater

- src/main/java/hudson/plugins/jira/selector/DefaultIssueSelector.java
This was incorrectly refactored into a recursive call.
This was changed from:
https://github.com/jenkinsci/jira-plugin/commit/2eace064c77979cab041e61d82dea47eb44cc886#diff-e381acd1474876247543cc9edc4ea09eL77
Into this:
https://github.com/jenkinsci/jira-plugin/commit/2eace064c77979cab041e61d82dea47eb44cc886#diff-e381acd1474876247543cc9edc4ea09eR134
If the detected changes happen to contain a lot of dependency changes, which can also detect a lot of dependency changes, the build can take a very long time.
JENKINS-46995 makes this bug more noticeable.
> Fix for JENKINS-44989 Updating JIRA-issues deadlock

- src/main/java/hudson/plugins/jira/versionparameter/JiraVersionParameterValue.java
- src/test/java/hudson/plugins/jira/versionparameter/JiraVersionParameterDefinitionTest.java
JENKINS-46573 - Ensure the #getValue() method is correctly overridden to ensure the step works correctly in pipelines.
> JENKINS-46573 - Fix version parameter to work in pipelines

- src/main/java/com/atlassian/httpclient/apache/httpcomponents/ApacheAsyncHttpClient.java
- src/test/java/com/atlassian/httpclient/apache/httpcomponents/ApacheAsyncHttpClientTest.java
https://issues.jenkins-ci.org/browse/JENKINS-51164
Added an Apache HttpClient RoutePlanner in order to handle the No Proxy Host setup from UI.
@olamy can you please review it as is clearly related to https://github.com/jenkinsci/jira-plugin/pull/148
> [JENKINS-51164] No Proxy Host setup from UI supported

- src/main/java/com/atlassian/httpclient/apache/httpcomponents/ApacheAsyncHttpClient.java
- src/main/java/com/atlassian/httpclient/apache/httpcomponents/DefaultHttpClientFactory.java
- src/main/java/com/atlassian/httpclient/apache/httpcomponents/DefaultRequest.java
- src/main/java/com/atlassian/httpclient/apache/httpcomponents/DefaultResponse.java
- src/main/java/com/atlassian/httpclient/apache/httpcomponents/Headers.java
- src/main/java/com/atlassian/httpclient/apache/httpcomponents/SettableFuturePromiseHttpPromiseAsyncClient.java
- src/main/java/hudson/plugins/jira/JiraBuildAction.java
- src/main/java/hudson/plugins/jira/JiraCreateIssueNotifier.java
- src/main/java/hudson/plugins/jira/JiraCreateReleaseNotes.java
- src/main/java/hudson/plugins/jira/JiraFolderProperty.java
- src/main/java/hudson/plugins/jira/JiraIssueUpdater.java
- src/main/java/hudson/plugins/jira/JiraProjectProperty.java
- src/main/java/hudson/plugins/jira/JiraRestService.java
- src/main/java/hudson/plugins/jira/JiraSession.java
- src/main/java/hudson/plugins/jira/JiraSite.java
- src/main/java/hudson/plugins/jira/JiraVersionCreatorBuilder.java
- src/main/java/hudson/plugins/jira/Updater.java
- src/main/java/hudson/plugins/jira/pipeline/IssueFieldUpdateStep.java
- src/main/java/hudson/plugins/jira/pipeline/IssueSelectorStep.java
- src/main/java/hudson/plugins/jira/selector/ExplicitIssueSelector.java
- src/main/java/hudson/plugins/jira/versionparameter/JiraVersionParameterDefinition.java
- src/main/java/hudson/plugins/jira/versionparameter/JiraVersionParameterValue.java
- src/main/java/hudson/plugins/jira/versionparameter/VersionComparator.java
- src/main/resources/hudson/plugins/jira/JiraSite/config.jelly
- src/main/resources/hudson/plugins/jira/JiraSite/help-readTimeout.html
- src/main/resources/hudson/plugins/jira/JiraSite/help-threadExecutorNumber.html
- src/test/java/JiraTester.java
- src/test/java/hudson/plugins/jira/DescriptorImpl2Test.java
- src/test/java/hudson/plugins/jira/DescriptorImplTest.java
- src/test/java/hudson/plugins/jira/JiraCreateIssueNotifierTest.java
> fix some strange http configuration confusion between connect timeout and read timeout

- src/main/resources/hudson/plugins/jira/JiraSite/config.jelly
[https://issues.jenkins-ci.org/browse/JENKINS-55787](https://issues.jenkins-ci.org/browse/JENKINS-55787)
Basically checkboxes should have labels, splitting the labels away from their checkboxes is poor UX, poor accessibility. This change brings the layout more inline with how normal settings UIs lay out checkboxes.
> [JENKINS-55787] Switch labels from entry to checkbox

- src/main/java/hudson/plugins/jira/JiraRestService.java
- src/main/java/hudson/plugins/jira/JiraSession.java
- src/main/java/hudson/plugins/jira/JiraSite.java
- src/main/java/hudson/plugins/jira/VersionCreator.java
- src/main/java/hudson/plugins/jira/VersionReleaser.java
- src/main/java/hudson/plugins/jira/extension/AsynchronousExtendedVersionRestClient.java
- src/main/java/hudson/plugins/jira/extension/ExtendedAsynchronousJiraRestClient.java
- src/main/java/hudson/plugins/jira/extension/ExtendedAsynchronousVersionRestClient.java
- src/main/java/hudson/plugins/jira/extension/ExtendedJiraRestClient.java
- src/main/java/hudson/plugins/jira/extension/ExtendedVersion.java
- src/main/java/hudson/plugins/jira/extension/ExtendedVersionInput.java
- src/main/java/hudson/plugins/jira/extension/ExtendedVersionInputJsonGenerator.java
- src/main/java/hudson/plugins/jira/extension/ExtendedVersionJsonParser.java
- src/main/java/hudson/plugins/jira/extension/ExtendedVersionRestClient.java
- src/main/java/hudson/plugins/jira/model/JiraVersion.java
- src/test/java/JiraTester.java
- src/test/java/hudson/plugins/jira/JiraReplaceFixVersionByRegExTest.java
- src/test/java/hudson/plugins/jira/JiraRestServiceTest.java
- src/test/java/hudson/plugins/jira/VersionCreatorTest.java
- src/test/java/hudson/plugins/jira/VersionReleaserTest.java
When creating a new version in Jira through Jenkins we want to set the current date in "Start Date" for Version Reports. Currently we have to manually edit them in Jira after each build in Jenkins.
This field was never added to the Jira Rest Java Client Library even though it is available on the Jira Rest API (undocumented).
If I query a particular version with a "Start Date" already filled in Jira, I can see the field "startDate".
`
{
"self": "https://.../rest/api/latest/version/21755",
"id": "21755",
"name": "CLAP-3.0.2",
"archived": false,
"released": false,
"startDate": "2019-03-14",
"userStartDate": "March 14, 2019",
"projectId": 12400
}
`
> [JENKINS-56810] Add current date in startDate when creating new version

- src/main/java/hudson/plugins/jira/Updater.java
When posting about an integrated build, use `getFullDisplayName()` instead of relying on default `toString()` behavior which does not consider display names.
The internal Jenkins build numbers don't mean much within the organization, so the Jira comments showing the commonly understood version number we use (e.g. 1.0.0.x) would be more desired. From https://github.com/jenkinsci/jenkins/blob/811583eb6007ffa22f81c312d983816e5f36a670/core/src/main/java/hudson/model/Run.java#L780-L796 it seems to be clear that the behavior is unchanged if custom display names are not set.
> Use display names in integrated build comments

- src/main/java/hudson/plugins/jira/JiraCreateIssueNotifier.java
- src/main/java/hudson/plugins/jira/JiraCreateReleaseNotes.java
- src/main/java/hudson/plugins/jira/JiraIssueMigrator.java
- src/main/java/hudson/plugins/jira/JiraIssueUpdater.java
- src/main/java/hudson/plugins/jira/JiraReleaseVersionUpdater.java
- src/main/java/hudson/plugins/jira/JiraVersionCreator.java
- src/main/java/hudson/plugins/jira/JiraVersionCreatorBuilder.java
- src/main/java/hudson/plugins/jira/RunScmChangeExtractor.java
- src/main/java/hudson/plugins/jira/Updater.java
- src/main/java/hudson/plugins/jira/selector/DefaultIssueSelector.java
- src/test/java/hudson/plugins/jira/JiraCreateIssueNotifierTest.java
- src/test/java/hudson/plugins/jira/UpdaterTest.java
- src/test/java/hudson/plugins/jira/selector/perforce/JobIssueSelectorTest.java
* Fix [JENKINS-33222](https://issues.jenkins-ci.org/browse/JENKINS-33222)
On our Jenkins instance, we have many jobs that build 3-4 builds in parallel, often with variable run times.  It's not uncommon for failed builds to end in just a few minutes, while lower-number builds are still running.
The JIRA plugin breaks this type of setup, because it blocks while waiting for the prior build to complete before it will report.  We'd like to use the JIRA plugin, but without blocking on prior builds.
* Change all references to `BuildStepMonitor.BUILD` to `BuildStepMonitor.NONE` (telling Jenkins we do not require the previous build to complete before running any of the plugin's Builders).
* Change all references to `getPreviousBuild()` to `getPreviousCompletedBuild()`.  By getting the last …
> [JENKINS-33222] Better support for parallel builds

- src/main/resources/hudson/plugins/jira/JiraFolderProperty/config.jelly
issue: [JENKINS-56951](https://issues.jenkins-ci.org/browse/JENKINS-56951)
When the folder properties list is built, it's already under a titled section see
https://github.com/jenkinsci/cloudbees-folder-plugin/blob/9d87f2f197554d93a97422a010bd92087e4e576b/src/main/resources/com/cloudbees/hudson/plugins/folder/AbstractFolder/configure.jelly#L136
Adding the section title in the JiraFolderProperty configuration file broken the layout
and let to think that the other properties (from other plugins) could be part of the Jira 
section as well.
Removing the title here fix that.
> [JENKINS-56951] Fix folder property layout

- src/main/java/hudson/plugins/jira/VersionReleaser.java
Sometimes versionDescription may be null. For example if it is created using Jenkins DSL plugin:
``` groovy
publishers { 
releaseJiraVersion {
projectKey('PROJECT')
release('$JiraBuild')
}
}
```
When versionDescription is null an NPE is thrown, and the job fails without showing a proper stack trace.
```
FATAL: Unable to release jira version <version>/<project>: java.lang.NullPointerException
Finished: FAILURE
```
This problem began showing up about three weeks to one month ago.
Here are the versions we are using:
Jenkins: 2.164.2
JIRA Plugin: 3.0.7
Job DSL Plugin: 1.72
This PR may potentially be related to https://issues.jenkins-ci.org/browse/JENKINS-57664 and be a fix for the problem mentioned in the ticket.
> Fix NPE when versionDescription is null

- .travis.yml
[`[ERROR] Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report (default-cli) on project jira: I/O operation failed: No coverage report files found -> [Help 1]`](https://travis-ci.org/jenkinsci/jira-plugin/builds/574628600#L604)
According to maven doc it is [`-DskipTests`](http://maven.apache.org/surefire/maven-surefire-plugin/examples/skipping-tests.html)
> Fix jacoco:report order, fix -DskipTests

- .travis.yml
Hopefully, this fixes the Travis cache. Seems that builds are always downloading 😓
> fix travis cache of maven repo

- src/main/java/hudson/plugins/jira/JiraCreateIssueNotifier.java
In some error scenarios `builds/issue.txt` can be an empty file.
I saw it on my system when Atlassian changed their REST API, and then suddenly many of my Jenkins jobs using the jira plugin started to fail, creting empty issue.txt files.
In this case, a job can never transition from failure to success, since it will read an empty issue.txt file, and then try to look up a JIRA Issue based on an empty id and fail.
> If issue.txt is empty, getIssue() should return null

- CHANGELOG.md
- src/main/java/hudson/plugins/jira/JiraCreateIssueNotifier.java
- src/test/java/hudson/plugins/jira/JiraCreateIssueNotifierTest.java
Instead of hardcoding three statuses to be recognized as "done" this PR switches to use the predefined status category "done".
The first commit bumps the dependencies because the status category was not exposed before.
The second commit should also work alone after #213 is merged.
> Accept all status that are in the "done" category as being done

- .travis.yml
- Jenkinsfile
- pom.xml
As JenkinsCI is sometimes failing and to have the parity with it in order not to confuse contributors, reenable normal full build on TravisCI too.
Replaces #223 
Reasons:
https://issues.jenkins-ci.org/browse/INFRA-2569
https://issues.jenkins-ci.org/browse/INFRA-2548
https://issues.jenkins-ci.org/browse/INFRA-2544
https://issues.jenkins-ci.org/browse/INFRA-2393
> Reenable full build on TravisCI

- .gitignore
- .idea/checkstyle-idea.xml
- .idea/google-java-format.xml
- README.md
This PR adds Google Java styleguide settings-only (for IDEA) and updates the README about the code style guide. It does not run any enforced checks nor does not contain any reformatting, but serves as a first step to improve gradually the codebase.
> Add Google codestyle rules

- src/main/java/hudson/plugins/jira/versionparameter/VersionComparator.java
- src/test/java/hudson/plugins/jira/versionparameter/VersionComparatorTest.java
We wanted to used the JIRa plugin in our Jenkins to add JIRA release Parameter, but we have project that contains (but used) strange name as version :
"201601-"
"COMPONENT-"
Due to the present of "-", the plugin try to parse it and expect something after the "-".
But in our case, it's not the case.
And it's failing, and that causes the list of the parameter to be empty.
Here is a small fix that avoid to throw exception in this case and allow to return the list of release.
> Avoid failure if there is malformed versions in the list

- pom.xml
When installing the plugin on a fresh install without any plugins installed, the *Manage* screen throws ClassNotFound error.
This should be a compilation failure, but since credentials plugin was coming from optional p4 dependency, the build was fine.
```
[INFO] +- org.jenkins-ci.plugins:p4:jar:1.3.8:compile (optional)
[INFO] |  +- org.jenkins-ci.plugins:credentials:jar:2.3.13:compile (optional)
```
> [JENKINS-64002] Fix optional dependencies to other Jenkins plugins

- src/main/java/hudson/plugins/jira/JiraBuildAction.java
Restore binary compatability. See https://github.com/jenkinsci/jira-plugin/pull/283/ , issue link https://issues.jenkins-ci.org/browse/JENKINS-64148
CC @warden
> [JENKINS-64148] Restore binary compatibility in JiraBuildAction

- src/main/java/hudson/plugins/jira/JiraChangeLogAnnotator.java
On a busy controller, the 'Annotating Jira id ...' messages can log thousands of entries per day, which makes it difficult to debug other issues using the service logs. I propose to reduce the log level to FINE so these messages are not logged by default.
https://issues.jenkins.io/browse/JENKINS-64988
> JENKINS-64988: Reduce log level of annotation messages

- src/main/java/hudson/plugins/jira/extension/ExtendedAsynchronousJiraRestClient.java
- src/main/java/hudson/plugins/jira/extension/ExtendedAsynchronousMyPermissionsRestClient.java
- src/main/java/hudson/plugins/jira/extension/ExtendedAsynchronousVersionRestClient.java
- src/main/java/hudson/plugins/jira/extension/UriBuilderHelper.java
When using this plugin with another plugin installed that also bundles a copy of the `javax.ws.rs` API, an error was reported of the form
```
java.lang.LinkageError: ClassCastException: attempting to cast jar:file:/JENKINS_HOME/plugins/some-other-plugin/WEB-INF/lib/javax.ws.rs-api-2.1.jar!/javax/ws/rs/ext/RuntimeDelegate.class to jar:file:/JENKINS_HOME/plugins/jira/WEB-INF/lib/jsr311-api-1.1.1.jar!/javax/ws/rs/ext/RuntimeDelegate.class
at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:116)
at javax.ws.rs.ext.RuntimeDelegate.getInstance(RuntimeDelegate.java:91)
at javax.ws.rs.core.UriBuilder.newInstance(UriBuilder.java:69)
at javax.ws.rs.core.UriBuilder.fromUri(UriBuilder.java:80)
at com.atlassian.jira.rest.client.internal.async.AsynchronousJiraRestClient.<init>(Asynchron …
```
> Ensure calls to `UriBuilder.fromUri` use a suitable `Thread.contextClassLoader`

- src/main/java/hudson/plugins/jira/JiraSite.java
When using the jira plugin from pipelines in Jenkinsfile runner, I see the following error on startup:
```
2021-06-23 13:37:34.724+0000 [id=49]	WARNING	h.model.listeners.RunListener#report: RunListener failed
java.lang.LinkageError: ClassCastException: attempting to castjar:file:/usr/share/jenkins/ref/plugins/codeship-interation-plugin.hpi/WEB-INF/lib/jboss-jaxrs-api_2.1_spec-2.0.1.Final.jar!/javax/ws/rs/ext/RuntimeDelegate.classtojar:file:/usr/share/jenkins/ref/plugins/jira.hpi/WEB-INF/lib/jsr311-api-1.1.1.jar!/javax/ws/rs/ext/RuntimeDelegate.class
at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:116)
at javax.ws.rs.ext.RuntimeDelegate.getInstance(RuntimeDelegate.java:91)
at javax.ws.rs.core.UriBuilder.newInstance(UriBuilder.java:69)
at …
```
> Fix `RuntimeDelegate` `ClassCastException` in Jira REST client init use of `UriBuilder.fromUri`.

- src/main/java/hudson/plugins/jira/JiraSite.java
- src/test/java/hudson/plugins/jira/JiraSiteTest.java
This change includes the update from Carsten Pfeiffer to address JENKINS-64083 as well as new test method in JiraSiteTest to verify the update.
> [JENKINS-64083] Updated JiraSite to use global credentials when no job-specific credentials are defined

- src/main/java/com/atlassian/httpclient/apache/httpcomponents/DefaultHttpClientFactory.java
- src/main/java/hudson/plugins/jira/CredentialsHelper.java
- src/main/java/hudson/plugins/jira/JiraBuildAction.java
- src/main/java/hudson/plugins/jira/JiraFolderProperty.java
- src/main/java/hudson/plugins/jira/JiraGlobalConfiguration.java
- src/main/java/hudson/plugins/jira/JiraJobAction.java
- src/main/java/hudson/plugins/jira/JiraProjectProperty.java
- src/main/java/hudson/plugins/jira/JiraRestService.java
- src/main/java/hudson/plugins/jira/JiraSession.java
- src/main/java/hudson/plugins/jira/JiraSite.java
- src/main/java/hudson/plugins/jira/extension/ExtendedVersion.java
- src/main/java/hudson/plugins/jira/extension/ExtendedVersionInput.java
- src/main/java/hudson/plugins/jira/model/JiraIssue.java
- src/main/java/hudson/plugins/jira/pipeline/CommentStep.java
- src/main/java/hudson/plugins/jira/pipeline/IssueSelectorStep.java
- src/main/java/hudson/plugins/jira/pipeline/SearchIssuesStep.java
- src/main/java/hudson/plugins/jira/selector/AbstractIssueSelector.java
- src/main/java/hudson/plugins/jira/selector/DefaultIssueSelector.java
- src/main/java/hudson/plugins/jira/selector/ExplicitIssueSelector.java
- src/test/java/com/atlassian/httpclient/apache/httpcomponents/ApacheAsyncHttpClientTest.java
- src/test/java/hudson/plugins/jira/JiraCreateIssueNotifierTest.java
Adapting to jenkinsci/jenkins#4604.
> Use findbugs annotations (as JSR 305 is dormant)

- src/main/java/hudson/plugins/jira/JiraMailAddressResolver.java
- src/test/java/hudson/plugins/jira/MailResolverDisabledTest.java
- src/test/java/hudson/plugins/jira/MailResolverWithExtensionTest.java
Signed-off-by: Olivier Lamy <olamy@apache.org>
> avoid NPE when outsite of a job context

- .github/dependabot.yml
- pom.xml
Guava is not up2date in Jenkins LTS so all the hard-coded hacks can be removed.
> remove guava as provided by core

- pom.xml
to avoid class path conflicts. Currently class path conflicts exist between [gitlab-api plugin](https://github.com/jenkinsci/gitlab-api-plugin) and jira plugin
cc @basil @dcendents
https://github.com/jenkinsci/jersey2-api-plugin/pull/19
> depend on jersey2-api

- pom.xml
- src/main/java/hudson/plugins/jira/JiraSite.java
- src/test/java/hudson/plugins/jira/ChangingWorkflowTest.java
- src/test/java/hudson/plugins/jira/JiraChangeLogAnnotatorTest.java
- src/test/java/hudson/plugins/jira/JiraCreateReleaseNotesTest.java
- src/test/java/hudson/plugins/jira/MailResolverWithExtensionTest.java
- src/test/java/hudson/plugins/jira/VersionCreatorTest.java
- src/test/java/hudson/plugins/jira/VersionReleaserTest.java
Remove powermock, slightly refactor `JiraSite` to make tests work with Mockito
* For consistency, to have a single mocking framework
* A requirement to modify object state via reflection (which Powermock is doing) to test it, indicates wrong design and should be fixed
https://github.com/jenkinsci/jira-plugin/issues/389
> Remove power-mock

- pom.xml
Jenkins plugins and other components should refer only to the Jenkins Artifactory (and implicitly anything it mirrors including of course Central), never to other Maven repositories. https://repo.jenkins-ci.org/ui/repos/tree/General/public aggregates https://repo.jenkins-ci.org/ui/repos/tree/General/atlassian which mirrors https://maven.atlassian.com/content/repositories/atlassian-public/
so there should be no need to explicitly specify it. Amends 0834935028b987bdb19bf9d672a684111b278526. Trying to fix a problem running https://github.com/jenkinsci/maven-hpi-plugin/pull/336 depending on mirror settings, though it does not seem to work anyway.
> Remove foreign `atlassian-public` repository

- src/test/java/hudson/plugins/jira/CliParameterTest.java
the build was started but it did not wait for the build to complete.
On windows this would cause a failure to cleanup in the teardown of the
Jenkins instance as the build log file would still be in use (sometimes)
Fixes the issue by [adding the -s flag](https://www.jenkins.io/doc/book/managing/cli/) to the build command so the cli
command will not return until the build has completed.
fixes for example https://ci.jenkins.io/job/Plugins/job/jira-plugin/job/master/354/testReport/junit/hudson.plugins.jira/CliParameterTest/windows_11___Build__windows_11____jiraVersionParameterViaCli/
> fix flaky CliParameterTest on Windows

- src/main/java/hudson/plugins/jira/EnvironmentExpander.java
- src/main/java/hudson/plugins/jira/pipeline/IssueFieldUpdateStep.java
- src/main/java/hudson/plugins/jira/selector/ExplicitIssueSelector.java
- src/main/java/hudson/plugins/jira/selector/JqlIssueSelector.java
- src/test/java/hudson/plugins/jira/EnvironmentExpanderTest.java
- src/test/java/hudson/plugins/jira/selector/ExplicitIssueSelectorTest.java
- src/test/java/hudson/plugins/jira/selector/JqlIssueSelectorTest.java
- Extract environment expansion to its own class (EnvironmentExpander)
- Call EnvironmentExpander from various steps and selectors
- IssueFieldUpdateStep
- ExplicitIssueSelector
- JqlIssueSelector
The "Environment variable expanding logic was already implemented". [Here](https://github.com/jenkinsci/jira-plugin/issues/460) is the detailed explanation of the issue.
What I did is, I moved the logic to its own class and used it in JqlIssueSelecter and ExplicitIssueSelector to parse it with environment variables before sending the data to jira service.
The logic was previously implemented in IssueFieldUpdateStep, so my changes on that class was just refactoring to use the new class.
--- …
> Environment Expansion for issue Ids on various steps and selectors

- src/main/java/hudson/plugins/jira/JiraRestService.java
- src/test/java/hudson/plugins/jira/JiraRestServiceProxyTest.java
Fix #459 
Using the no_proxy_host configuration from Jenkins to enable or not the activation of the proxy in the Request.
Test added to check to verify the implementation.
I also use a snapshot version with this fix internally.
> Use No Proxy Hosts configuration

- pom.xml
- src/main/java/hudson/plugins/jira/JiraSession.java
- src/main/java/hudson/plugins/jira/JiraSite.java
This repository can be trivially made to conform to our upstream Javadoc configuration of `<doclint>all,-missing</doclint>`, removing the need to maintain a custom configuration and simplifying maintenance. Tested locally with `mvn clean verify -Pjenkins-release`.
> Use upstream Javadoc configuration

- pom.xml
Removes these JARs from the HPI:
- `WEB-INF/lib/commons-codec-1.15.jar`
- `WEB-INF/lib/commons-io-2.11.0.jar`
- `WEB-INF/lib/jettison-1.5.4.jar`
- `WEB-INF/lib/jsr305-3.0.1.jar`
- `WEB-INF/lib/slf4j-api-2.0.3.jar`
SLF4J, Commons Codec, and Commons IO are already provided by Jenkins core. Due to how [plugin class loading works in Jenkins](https://www.jenkins.io/doc/developer/plugin-development/dependencies-and-class-loading/), core's copy is always first and the plugin copy is never visible. So it is just a waste of space to bundle it in the HPI, since it is never used.
Jettison is similarly already bundled in the Jersey 2 API plugin, which is on the classpath via a plugin-to-plugin dependency.
JSR 305 is not needed at runtime and is deprecated. Throughout the whole Jenkins project, we …
> Slim down HPI

- Jenkinsfile
- src/test/java/hudson/plugins/jira/JiraCreateReleaseNotesTest.java
See [JENKINS-71957](https://issues.jenkins.io/browse/JENKINS-71957).
When building the plugin with Java 17 and less, everything is fine but once building with Java 20+, there is a NPE occurring in the test.
This is because when testing with invalid setup, the exception is supposed to be printed out. However, the way the exceptions are printed changed. More specifically, the way a lock is acquired in order to print the exceptions. This should have no consequences on any code, as it is internal change of the JVM, but in the current plugin it creates a NPE are the object used to get the lock is a `mock` which is not properly initialized in the test class.
I ran `mvn clean verify` with Java 17 an no issue happened.
I ran `mvn clean verify` with both Java 20 and 21 and then both …
> [JENKINS-71957] Fix support for Java 21

- pom.xml
Stop bundling an unnecessary copy of Joda Time; instead, implement dynamic linking by depending on @jonesbusy's new [Joda Time](https://plugins.jenkins.io/joda-time-api/) library plugin. This, in turn, results in updating the baseline (to use the newest BOM release where the Joda Time library plugin is present), but this bump is in accordance with [the official recommendations](https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/).
> Implement dynamic linking of Joda Time

- src/main/java/hudson/plugins/jira/JiraSite.java
- src/test/java/com/atlassian/httpclient/apache/httpcomponents/ApacheAsyncHttpClientTest.java
Annotations for Nonnull, CheckForNull, and several others were proposed for Java as part of dormant Java specification request JSR-305. The proposal never became a part of standard Java.
Jenkins plugins should switch from using JSR-305 annotations to use Spotbugs annotations that provide the same semantics.
The [mailing list discussion](https://groups.google.com/g/jenkinsci-dev/c/uE1wwtVi1W0/m/gLxdEJmlBQAJ) from James Nord describes the affected annotations and why they should be replaced with annotations that are actively maintained.
The ["Improve a plugin" tutorial](https://www.jenkins.io/doc/developer/tutorial-improve/replace-jsr-305-annotations/) provides instructions to perform this change.
An [OpenRewrite recipe](https://docs.openrewrite.org/recipes/jenkins/javaxannotationstospotbugs …
> Replace JSR-305 annotations with spotbugs annotations

- .github/ISSUE_TEMPLATE/1-report-bug.yml
- .github/ISSUE_TEMPLATE/2-feature-request.yml
- .gitignore
- src/main/java/hudson/plugins/jira/JiraRestService.java
- src/main/java/hudson/plugins/jira/JiraSession.java
Fixes needed for release requested by upstream in #636.
- Set a hardcoded limit of 100 issues to be returned in searchJql() call to fix #646:
> RestClientException{statusCode=Optional.of(400), errorCollections=[ErrorCollection{status=400, errors={}, errorMessages=[The max results parameter has to be between 1 and 5,000.]}]}
- Set explicitly the fields that are needed according to documentation, since passing `null` doesn't work:
> 2025-04-22 21:27:52.779+0000 [id=31]	WARNING	h.plugins.jira.JiraRestService#getIssuesFromJqlSearch: Jira REST client get issue from jql search error. cause: RestClientException{statusCode=Optional.absent(), errorCollections=[]}
org.codehaus.jettison.json.JSONException: JSONObject["fields"] not found.
> Bug fixes for Jira REST Java client

- .gitignore
- pom.xml
Code coverage reports are missing for a long time and it seems that the custom JDK17 profile is causing this. The [add-opens are now handled in plugin-pom](https://github.com/jenkinsci/plugin-pom/blob/master/pom.xml#L66) so this profile shouldn't be needed anymore.
> remove jdk17 custom profile

- src/main/java/hudson/plugins/jira/listissuesparameter/JiraIssueParameterDefinition.java
- src/test/java/hudson/plugins/jira/listissuesparameter/JiraIssueParameterTest.java
> Add support for jira issue parameter in pipelines

- src/main/java/hudson/plugins/jira/JiraSession.java
- src/test/java/JiraTester.java
- src/test/java/JiraTesterBearerAuth.java
- src/test/java/hudson/plugins/jira/JiraReplaceFixVersionByRegExTest.java
Use JiraSession.MAX_ISSUES constant around the codebase and fix remaining calls consistently.
> Fix other JiraSession MAX_INTEGER instances via re-used static constant

- src/main/java/hudson/plugins/jira/JiraRestService.java
https://github.com/jenkinsci/jira-plugin/issues/678
Search from Jql did not include field fixVersions, because of that fixVersions were always null. 
As a result it was always replacing all the existing fixVersions in the issues with the target release.
So I included fixVersions field in needed fields.
> Fix add target release option

- docs/_sidebar.md
- docs/changelog.md
- src/main/java/hudson/plugins/jira/listissuesparameter/JiraIssueParameterValue.java
- src/test/java/hudson/plugins/jira/listissuesparameter/JiraIssueParameterTest.java
Fixes #724 by returning an empty string in case the jiraIssue parameter is null.
> fix: don't throw NPE if no issues are returned from JiraParameterValue selector

- src/main/java/hudson/plugins/jira/JiraEnvironmentContributingAction.java
- src/test/java/hudson/plugins/jira/JiraEnvironmentContributingActionTest.java
When used with git-polling, some parameters passed to the action can be null, so take care of this graciously.
Fixes #735
> handle null values in JiraEnvironmentContributingAction
