src/main/java/hudson/plugins/jira/JiraProjectProperty.java, src/test/java/hudson/plugins/jira/EmptyFriendlyURLConverterTest.java
https://issues.jenkins-ci.org/browse/JENKINS-30242
Instead use the toString method
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/jenkinsci/jira-plugin/60)
=> [FIXES JENKINS-30242] don't cast object in converter to string

src/main/java/hudson/plugins/jira/Updater.java
Changes "Integrated in some-job #111" to "Integrated in Jenkins build some-job #111" and also adds the word "JIRA" in one other logging spot where it makes the line 1% better.
=> Simple wording additions

src/main/java/hudson/plugins/jira/JiraCreateIssueNotifier.java, src/main/java/hudson/plugins/jira/JiraRestService.java, src/main/java/hudson/plugins/jira/JiraSession.java
…erge - this was already changed in master.
=> JENKINS-30682 - Fix NPE on empty Component list in JIRA project. 

src/main/webapp/help-version-create.html
new pull request for #75 added missing help file referenced by JiraVersionCreator
=> added missing help file referenced by JiraVersionCreator

src/main/java/hudson/plugins/jira/VersionReleaser.java, src/main/resources/hudson/plugins/jira/Messages.properties, src/test/java/hudson/plugins/jira/JiraReleaseVersionUpdaterTest.java
use resource bundle instead of string constant, also print a message on success)
=> console message improvement for VersionReleaser

src/main/java/hudson/plugins/jira/Updater.java
When adding a comment and scam changes are recorded, make sure to add the edit type as well.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/jenkinsci/jira-plugin/57)
=> Include edit type in the affected files

README.md, pom.xml, src/main/java/hudson/plugins/jira/Updater.java, src/main/java/hudson/plugins/jira/listissuesparameter/JiraIssueParameterDefinition.java, src/main/java/hudson/plugins/jira/listissuesparameter/JiraIssueParameterValue.java, src/main/java/hudson/plugins/jira/versionparameter/JiraVersionParameterValue.java, src/test/groovy/hudson/plugins/jira/VersionComparatorTest.groovy, src/test/java/hudson/plugins/jira/CliParameterTest.java, src/test/java/hudson/plugins/jira/listissuesparameter/CliParameterTests.java
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/jenkinsci/jira-plugin/80)
=> CLI parameter submission for JiraIssueParameter

src/main/java/hudson/plugins/jira/JiraSite.java, src/test/java/hudson/plugins/jira/JiraCreateReleaseNotesTest.java
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/jenkinsci/jira-plugin/84)
=> JENKINS-32106: fixed UNKNOWN in release notes

COMPATIBILITY.md, pom.xml, src/main/java/hudson/plugins/jira/pipeline/CommentStep.java, src/main/java/hudson/plugins/jira/pipeline/SearchIssuesStep.java, src/main/resources/hudson/plugins/jira/Messages.properties, src/main/resources/hudson/plugins/jira/pipeline/CommentStep/config.jelly, src/main/resources/hudson/plugins/jira/pipeline/SearchIssuesStep/config.jelly, src/test/java/hudson/plugins/jira/pipeline/CommentStepTest.java, src/test/java/hudson/plugins/jira/pipeline/SearchIssuesStepTest.java
I create a specialized workflow steps that make it easy to use actions from Jenkins workflow plugin.
* search for an issues based on jql query
* post a arbitrary comment to defined issue
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/jenkinsci/jira-plugin/81)
=> Custom Workflow Pipeline steps

COMPATIBILITY.md, src/main/java/hudson/plugins/jira/JiraIssueUpdateBuilder.java
Modify JiraIssueUpdateBuilder to be compatible with Pipeline plugin.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/jenkinsci/jira-plugin/86)
=> JiraIssueUpdateBuilder Pipeline plugin compatibility

COMPATIBILITY.md, src/main/java/hudson/plugins/jira/JiraCreateReleaseNotes.java, src/test/java/hudson/plugins/jira/BuildListenerResultMethodMock.java, src/test/java/hudson/plugins/jira/JiraCreateReleaseNotesTest.java
Modify JiraCreateReleaseNotes to be compatible with Pipeline plugin.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/jenkinsci/jira-plugin/87)
=> JiraCreateReleaseNotes Pipeline plugin compatibility

COMPATIBILITY.md, src/main/java/hudson/plugins/jira/JiraReleaseVersionUpdaterBuilder.java, src/main/java/hudson/plugins/jira/VersionReleaser.java, src/test/java/hudson/plugins/jira/JiraReleaseVersionUpdaterBuilderTest.java
Modify JiraReleaseVersionUpdaterBuilder to be compatible with Pipeline plugin.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/jenkinsci/jira-plugin/88)
=> JiraReleaseVersionUpdaterBuilder Pipeline plugin compatibility

COMPATIBILITY.md, src/main/java/hudson/plugins/jira/pipeline/IssueSelectorStep.java, src/main/resources/hudson/plugins/jira/Messages.properties
New pipeline step jiraIssueSelector and some documentation by examples.
[<img src="https://reviewable.io/review_button.svg" height="41" alt="Review on Reviewable"/>](https://reviewable.io/reviews/jenkinsci/jira-plugin/89)
=> [JENKINS-32504] JiraEnvironmentVariableBuilder and pipeline plugin

src/main/java/hudson/plugins/jira/Updater.java
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jenkinsci/jira-plugin/92)
=> JENKINS-33551: fix NPE on labels in Updater.submitComments()

src/main/java/hudson/plugins/jira/Updater.java
Added NP check after retrieving the issue from the API.
https://issues.jenkins-ci.org/browse/JENKINS-33859
@reviewbybees
=> [JENKINS-33859] NPE Error updating JIRA issues

src/main/java/hudson/plugins/jira/JiraIssueMigrator.java, src/main/java/hudson/plugins/jira/JiraSession.java, src/main/java/hudson/plugins/jira/JiraSite.java, src/main/resources/hudson/plugins/jira/JiraIssueMigrator/config.jelly, src/main/resources/hudson/plugins/jira/JiraIssueMigrator/help-addRelease.html, src/test/java/hudson/plugins/jira/JiraIssueMigratorTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jenkinsci/jira-plugin/98)
=> Feature: Possibility to add fix version to list instead of replacing whole list or specific version

src/main/java/hudson/plugins/jira/pipeline/IssueSelectorStep.java, src/main/java/hudson/plugins/jira/selector/ExplicitIssueSelector.java, src/main/java/hudson/plugins/jira/selector/JqlIssueSelector.java, src/main/resources/hudson/plugins/jira/Messages.properties, src/main/resources/hudson/plugins/jira/pipeline/IssueSelectorStep/config.jelly, src/main/resources/hudson/plugins/jira/selector/ExplicitIssueSelector/config.jelly, src/main/resources/hudson/plugins/jira/selector/JqlIssueSelector/config.jelly
Make the selectors available in issueSelector step snippet generator.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jenkinsci/jira-plugin/99)
=> JENKINS-33996 improved issue selector pipeline snippet generator

src/main/java/hudson/plugins/jira/JiraVersionCreator.java, src/main/java/hudson/plugins/jira/JiraVersionCreatorBuilder.java, src/main/java/hudson/plugins/jira/VersionCreator.java, src/main/resources/hudson/plugins/jira/Messages.properties, src/test/java/hudson/plugins/jira/JiraVersionCreatorBuilderTest.java
Gives the possibility to create new JIRA version as a build step. With that user can create multiple versions in the single build process and can trigger creation conditionally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jenkinsci/jira-plugin/102)
=> Add JIRA version creation as a build step.

src/main/java/hudson/plugins/jira/JiraProjectProperty.java
Replaced AbstractProject with Job in JiraProjectProperty.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jenkinsci/jira-plugin/106)
=> JENKINS-38142 Posibility to specify JIRA site in jenkins pipeline project

src/main/java/hudson/plugins/jira/JiraChangeLogAnnotator.java, src/main/java/hudson/plugins/jira/Updater.java, src/main/java/hudson/plugins/jira/selector/DefaultIssueSelector.java, src/test/java/hudson/plugins/jira/JiraEnvironmentVariableBuilderTest.java, src/test/java/hudson/plugins/jira/JiraReleaseVersionUpdaterBuilderTest.java, src/test/java/hudson/plugins/jira/UpdaterTest.java, src/test/java/hudson/plugins/jira/selector/DefaultIssueSelectorTest.java
@johnou this contains the feedback you requested + fixed tests from #108 
Apologies for the breakages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jenkinsci/jira-plugin/115)
=> Fix calculation of server URL for JiraBuildAction

.travis.yml, pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jenkinsci/jira-plugin/116)
=> Bring back coverage

src/main/java/hudson/plugins/jira/JiraCreateIssueNotifier.java
…A ticket on success builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jenkinsci/jira-plugin/117)
=> Treat Resolved as Closed to create new JIRA instead of commenting old one

src/main/java/hudson/plugins/jira/EmptyFriendlyURLConverter.java, src/main/java/hudson/plugins/jira/JiraFolderProperty.java, src/main/java/hudson/plugins/jira/JiraProjectProperty.java, src/main/java/hudson/plugins/jira/JiraSite.java, src/main/resources/hudson/plugins/jira/JiraFolderProperty/config.jelly, src/main/resources/hudson/plugins/jira/Messages.properties, src/test/groovy/hudson/plugins/jira/JiraFolderPropertyTest.groovy, src/test/groovy/hudson/plugins/jira/JiraSiteTest.groovy, src/test/java/hudson/plugins/jira/EmptyFriendlyURLConverterTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jenkinsci/jira-plugin/124)
=> JENKINS-44524 Support configuring a site on a folder

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jenkinsci/jira-plugin/128)
=> JENKINS-45992 : Adding missing runtime atlassian fugue dependency

src/main/java/hudson/plugins/jira/JiraIssueUpdateBuilder.java, src/main/java/hudson/plugins/jira/JiraRestService.java, src/main/java/hudson/plugins/jira/JiraSession.java, src/main/java/hudson/plugins/jira/JiraSite.java, src/main/java/hudson/plugins/jira/listissuesparameter/JiraIssueParameterDefinition.java, src/main/java/hudson/plugins/jira/selector/JqlIssueSelector.java, src/test/java/hudson/plugins/jira/ChangingWorkflowTest.java, src/test/java/hudson/plugins/jira/JiraCreateReleaseNotesTest.java, src/test/java/hudson/plugins/jira/JiraIssueMigratorTest.java, src/test/java/hudson/plugins/jira/JiraIssueUpdateBuilderTest.java, src/test/java/hudson/plugins/jira/JiraReplaceFixVersionByRegExTest.java, src/test/java/hudson/plugins/jira/JiraRestServiceTest.java, src/test/java/hudson/plugins/jira/selector/JqlIssueSelectorTest.java
Fix for JENKINS-46243. Fails the build step when TimeoutException occurs instead of silently finishing.
=> [JENKINS-46243] Failing build on TimeoutException

src/main/java/hudson/plugins/jira/JiraChangeLogAnnotator.java, src/main/java/hudson/plugins/jira/JiraSite.java, src/main/resources/hudson/plugins/jira/JiraSite/config.jelly, src/main/resources/hudson/plugins/jira/JiraSite/help-disableChangelogAnnotations.html
@reviewbybees
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jenkinsci/jira-plugin/118)
=> [WIP] Option to disable jira annotating the changelogs.

.travis.yml, Jenkinsfile, pom.xml, src/main/java/hudson/plugins/jira/RunScmChangeExtractor.java, src/main/resources/hudson/plugins/jira/JiraBuildAction/summary.jelly, src/main/resources/hudson/plugins/jira/JiraCreateIssueNotifier/config.jelly, src/main/resources/hudson/plugins/jira/JiraCreateReleaseNotes/config.jelly, src/main/resources/hudson/plugins/jira/JiraEnvironmentVariableBuilder/config.jelly, src/main/resources/hudson/plugins/jira/JiraFolderProperty/config.jelly, src/main/resources/hudson/plugins/jira/JiraIssueMigrator/config.jelly, src/main/resources/hudson/plugins/jira/JiraIssueUpdateBuilder/config.jelly, src/main/resources/hudson/plugins/jira/JiraIssueUpdater/config.jelly, src/main/resources/hudson/plugins/jira/JiraProjectProperty/config.jelly, src/main/resources/hudson/plugins/jira/JiraProjectProperty/global.jelly, src/main/resources/hudson/plugins/jira/JiraReleaseVersionUpdater/config.jelly, src/main/resources/hudson/plugins/jira/JiraReleaseVersionUpdaterBuilder/config.jelly, src/main/resources/hudson/plugins/jira/JiraSite/config.jelly, src/main/resources/hudson/plugins/jira/JiraVersionCreator/config.jelly, src/main/resources/hudson/plugins/jira/JiraVersionCreatorBuilder/config.jelly, src/main/resources/hudson/plugins/jira/MavenJiraIssueUpdater/config.jelly, src/main/resources/hudson/plugins/jira/listissuesparameter/JiraIssueParameterDefinition/config.jelly, src/main/resources/hudson/plugins/jira/listissuesparameter/JiraIssueParameterDefinition/index.jelly, src/main/resources/hudson/plugins/jira/listissuesparameter/JiraIssueParameterValue/value.jelly, src/main/resources/hudson/plugins/jira/selector/DefaultIssueSelector/config.jelly, src/main/resources/hudson/plugins/jira/selector/perforce/P4JobIssueSelector/config.jelly, src/main/resources/hudson/plugins/jira/selector/perforce/PerforceJobIssueSelector/config.jelly, src/main/resources/hudson/plugins/jira/versionparameter/JiraVersionParameterDefinition/config.jelly, src/main/resources/hudson/plugins/jira/versionparameter/JiraVersionParameterDefinition/index.jelly, src/main/resources/hudson/plugins/jira/versionparameter/JiraVersionParameterValue/value.jelly, src/main/resources/index.jelly
=> Various POM mistakes

.travis.yml, pom.xml
=> [WIP] move to jacoco as cobertura is not really maintain anymore

pom.xml
=> [JENKINS-51312] upgrade core to 2.60.1

pom.xml
=> [WIP] [JENKINS-51310] Update JIRA plugin to use jackson2-api-plugin

src/main/java/hudson/plugins/jira/JiraChangeLogAnnotator.java, src/main/java/hudson/plugins/jira/JiraCreateIssueNotifier.java, src/main/java/hudson/plugins/jira/JiraIssueUpdateBuilder.java, src/main/java/hudson/plugins/jira/JiraMailAddressResolver.java, src/main/java/hudson/plugins/jira/JiraSession.java, src/main/java/hudson/plugins/jira/JiraSite.java, src/main/java/hudson/plugins/jira/Updater.java, src/main/java/hudson/plugins/jira/pipeline/CommentStep.java, src/main/java/hudson/plugins/jira/pipeline/IssueFieldUpdateStep.java, src/main/java/hudson/plugins/jira/pipeline/SearchIssuesStep.java, src/main/java/hudson/plugins/jira/selector/DefaultIssueSelector.java, src/main/java/hudson/plugins/jira/selector/JqlIssueSelector.java, src/test/java/hudson/plugins/jira/JiraChangeLogAnnotatorTest.java, src/test/java/hudson/plugins/jira/UpdaterTest.java
`JiraSite` is a giant class now, i want to decompose it in pieces. This is a first step which basically cleans up some unused and deprecated code. In the next PR i want to move some methods (e.g. `getReleaseNotesForFixVersion`) to places where they belong.
=> Decomposing JiraSite part 1

src/main/java/hudson/plugins/jira/JiraSite.java
=> simplify code

src/main/java/hudson/plugins/jira/JiraSite.java, src/test/java/hudson/plugins/jira/JiraSiteSecurity1029Test.java
=> [JENKINS-54144] ensure nThreads cannot be lower 1

src/main/java/hudson/plugins/jira/JiraSite.java, src/test/java/hudson/plugins/jira/DescriptorImpl2Test.java, src/test/java/hudson/plugins/jira/JiraSite2Test.java
Did the review cleanup from: https://github.com/jenkinsci/jira-plugin/pull/173
=> Simplify constructor, main URL is the only mandatory field

src/test/java/hudson/plugins/jira/CliParameterTest.java, src/test/java/hudson/plugins/jira/CredentialsHelperTest.java, src/test/java/hudson/plugins/jira/DescriptorImpl2Test.java, src/test/java/hudson/plugins/jira/DescriptorImplTest.java, src/test/java/hudson/plugins/jira/JiraBuildActionTest.java, src/test/java/hudson/plugins/jira/JiraChangeLogAnnotatorTest.java, src/test/java/hudson/plugins/jira/JiraCreateIssueNotifierTest.java, src/test/java/hudson/plugins/jira/JiraCreateReleaseNotesTest.java, src/test/java/hudson/plugins/jira/JiraEnvironmentVariableBuilderTest.java, src/test/java/hudson/plugins/jira/JiraIssueMigratorTest.java, src/test/java/hudson/plugins/jira/JiraIssueUpdateBuilderTest.java, src/test/java/hudson/plugins/jira/JiraIssueUpdaterTest.java, src/test/java/hudson/plugins/jira/JiraJobActionTest.java, src/test/java/hudson/plugins/jira/JiraReplaceFixVersionByRegExTest.java, src/test/java/hudson/plugins/jira/JiraRestServiceTest.java, src/test/java/hudson/plugins/jira/JiraSite2Test.java, src/test/java/hudson/plugins/jira/UpdaterTest.java, src/test/java/hudson/plugins/jira/pipeline/CommentStepTest.java, src/test/java/hudson/plugins/jira/pipeline/SearchIssuesStepTest.java, src/test/java/hudson/plugins/jira/selector/DefaultIssueSelectorTest.java, src/test/java/hudson/plugins/jira/selector/ExplicitIssueSelectorTest.java, src/test/java/hudson/plugins/jira/selector/JqlIssueSelectorTest.java, src/test/java/hudson/plugins/jira/selector/perforce/JobIssueSelectorTest.java, src/test/java/hudson/plugins/jira/selector/perforce/P4JobIssueSelectorTest.java, src/test/java/hudson/plugins/jira/versionparameter/JiraVersionParameterDefinitionTest.java
consistency is key as discovered in #168 :trollface:
=> The word test in test method is a nono

.travis.yml, pom.xml, src/main/java/hudson/plugins/jira/JiraSite.java, src/test/java/hudson/plugins/jira/DescriptorImplTest.java
=> [JENKINS-58244] https://issues.jenkins-ci.org/browse/JENKINS-58244

src/main/java/hudson/plugins/jira/pipeline/IssueSelectorStep.java, src/test/java/hudson/plugins/jira/pipeline/IssueSelectorStepTest.java
https://issues.jenkins-ci.org/browse/JENKINS-59001
@olamy are you able to take a look? 
Thanks.
=> JENKINS-59001 - IssueSelectorStep should handle NullPointerException caused by having no configured sites

src/main/java/hudson/plugins/jira/JiraGlobalConfiguration.java, src/test/java/hudson/plugins/jira/JiraGlobalConfigurationSaveTest.java
=> [JENKINS-57899] - fix saving global config

src/main/java/hudson/plugins/jira/listissuesparameter/JiraIssueParameterDefinition.java, src/main/resources/hudson/plugins/jira/listissuesparameter/JiraIssueParameterDefinition/config.jelly, src/main/resources/hudson/plugins/jira/listissuesparameter/JiraIssueParameterDefinition/help-altSummaryFields.html, src/test/java/hudson/plugins/jira/CliParameterTest.java, src/test/java/hudson/plugins/jira/JiraIssueParameterDefResultTest.java
Sometimes it would be useful to use a different Jira issue field or fields and the title in the issue selector dropdown.
=> JENKINS-60271:  Allow selection of field(s) for Issue selector display

.travis.yml, pom.xml
This should fix the TravisCI build.
ref: https://docs.travis-ci.com/user/job-lifecycle/
=> Bump OWASP to 5.3.0

pom.xml, src/main/java/com/atlassian/httpclient/apache/httpcomponents/ApacheAsyncHttpClient.java, src/main/java/com/atlassian/httpclient/apache/httpcomponents/DefaultMessage.java, src/main/java/com/atlassian/httpclient/apache/httpcomponents/DefaultRequest.java, src/main/java/com/atlassian/httpclient/apache/httpcomponents/DefaultResponse.java, src/main/java/com/atlassian/httpclient/apache/httpcomponents/PromiseHttpAsyncClient.java, src/main/java/com/atlassian/httpclient/apache/httpcomponents/RequestEntityEffect.java, src/main/java/com/atlassian/httpclient/apache/httpcomponents/SettableFuturePromiseHttpPromiseAsyncClient.java, src/main/java/hudson/plugins/jira/JiraRestService.java, src/main/java/hudson/plugins/jira/extension/ExtendedAsynchronousMyPermissionsRestClient.java, src/main/java/hudson/plugins/jira/extension/ExtendedAsynchronousVersionRestClient.java, src/main/java/hudson/plugins/jira/extension/ExtendedMyPermissionsRestClient.java, src/main/java/hudson/plugins/jira/extension/ExtendedVersionRestClient.java, src/test/java/hudson/plugins/jira/JiraCreateIssueNotifierTest.java, src/test/java/hudson/plugins/jira/JiraRestServiceTest.java
JENKINS-53794 JENKINS-56987 Bump to jira rest client 5.2.0
This is taken from: https://github.com/jenkinsci/jira-plugin/pull/212
See also:
*  https://bitbucket.org/atlassian/jira-rest-java-client/pull-requests/93 
*  https://bitbucket.org/atlassian/jira-rest-java-client/pull-requests/93/jrjc-240-added-support-for-accountid/d
=> JENKINS-53794 JENKINS-56987 Bump to jira rest client 5.2.1

pom.xml, src/main/java/hudson/plugins/jira/JiraSite.java, src/test/java/hudson/plugins/jira/JiraSiteSecurity1029Test.java
=> fix pct tests failing

src/main/java/com/atlassian/httpclient/apache/httpcomponents/ApacheAsyncHttpClient.java, src/main/java/com/atlassian/httpclient/apache/httpcomponents/SettableFuturePromiseHttpPromiseAsyncClient.java, src/test/java/com/atlassian/httpclient/apache/httpcomponents/SettableFuturePromiseHttpPromiseAsyncClientTest.java
All credits to https://github.com/xft-devs/jira-plugin
=> [JENKINS-60536] bugfix: Jenkins job hangs in Jira call after git rev-list command

src/main/java/hudson/plugins/jira/JiraRestService.java
=> [JENKINS-62638] Send both assignee fields when creating an issue

src/main/java/hudson/plugins/jira/JiraSite.java
=> [JENKINS-62703] restore backward compat for Blue Ocean

src/main/java/hudson/plugins/jira/pipeline/CommentStep.java, src/main/java/hudson/plugins/jira/pipeline/IssueSelectorStep.java, src/main/java/hudson/plugins/jira/pipeline/SearchIssuesStep.java
Replacing deprecated usages of Guice with their non-deprecated non-Guice equivalents.
=> Remove usages of Guice

src/main/java/hudson/plugins/jira/JiraRestService.java, src/test/java/hudson/plugins/jira/JiraRestServiceProxyTest.java
Use Jenkins Proxy-Settings for getVersions and other calls at JiraRestService
fix #385
=> [JENKINS-25829] Use proxy settings for REST API calls

pom.xml, src/test/java/hudson/plugins/jira/ChangingWorkflowTest.java, src/test/java/hudson/plugins/jira/CredentialsHelperTest.java, src/test/java/hudson/plugins/jira/JiraCreateIssueNotifierTest.java, src/test/java/hudson/plugins/jira/JiraCreateReleaseNotesTest.java, src/test/java/hudson/plugins/jira/JiraEnvironmentContributingActionTest.java, src/test/java/hudson/plugins/jira/UpdaterTest.java, src/test/java/hudson/plugins/jira/pipeline/CommentStepTest.java, src/test/java/hudson/plugins/jira/selector/JqlIssueSelectorTest.java
=> Update plugin POM and BOM

src/main/resources/hudson/plugins/jira/listissuesparameter/JiraIssueParameterDefinition/index.jelly, src/main/resources/hudson/plugins/jira/listissuesparameter/JiraIssueParameterValue/value.jelly, src/main/resources/hudson/plugins/jira/versionparameter/JiraVersionParameterDefinition/index.jelly, src/main/resources/hudson/plugins/jira/versionparameter/JiraVersionParameterValue/value.jelly
@olamy Didn't know whether you want this commit, or the one from `3.7.x`, up to you 🙂
=> Integrate SECURITY-2691 fix into default branch

pom.xml
Hi, I noticed there is a [commons-lang3-api plugin](https://plugins.jenkins.io/commons-lang3-api/) now. I thought jira-plugin would be a good candidate for adopting commons-lang3-api, since other plugins that may also need commons-lang3 rely on it (ex: artifactory), and similar api plugins (ex: jackson2-api) have already been adopted.
See https://github.com/jenkinsci/jenkins/pull/6267#issuecomment-1036644004 for details on plugin introduction. 
=> Depend on commons-lang3-api plugin

pom.xml, src/main/java/hudson/plugins/jira/JiraGlobalConfiguration.java, src/main/java/hudson/plugins/jira/JiraSite.java
Hi!
This PR aims to move this plugin to the [recommended](https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/) Jenkins baseline version.
If there are additional requirements for accepting PRs - such as additional lag time before adopting a baseline - feel free to reply in the comments.
Ran `mvn clean verify`.
I found a [new SpotBugs rule](https://github.com/spotbugs/spotbugs/blob/master/CHANGELOG.md#added-2) started failing, so I added `SuppressFBWarnings` annotations to retain backwards compatibility. It would also be possible to make the public fields private, but I opted to suppress to avoid breaking changes.
```[tasklist]
```
Refs: sghill-rewrite/campaigns#4
Closes #610
Use this link to re-run the recipe: …
=> Modernize to Jenkins 2.440.3

src/test/java/hudson/plugins/jira/JiraSiteSecurity1029Test.java
When testing this plugin against EE 10, I found the same test-only (not production) issues in `GitHubServerConfigIntegrationTest` as I did when testing this plugin against EE 9. Rather than continue to adapt this test for every EE version, this PR removes any references to Jetty or Jakarta EE from the test, making the test less fragile. In their place, we substitute references to standard Java Platform functionality.
`mvn clean verify` with Java 21
=> Convert test to `com.sun.net.httpserver`

src/main/java/hudson/plugins/jira/versionparameter/JiraVersionParameterDefinition.java, src/test/java/hudson/plugins/jira/versionparameter/JiraReleaseVersionParameterTest.java
=> Add support for jira version parameter in pipelines

pom.xml, src/main/java/hudson/plugins/jira/JiraIssueUpdateBuilder.java, src/main/java/hudson/plugins/jira/JiraIssueUpdater.java, src/main/java/hudson/plugins/jira/JiraReleaseVersionUpdaterBuilder.java, src/main/java/hudson/plugins/jira/JiraVersionCreatorBuilder.java, src/main/java/hudson/plugins/jira/pipeline/IssueFieldUpdateStep.java, src/test/java/hudson/plugins/jira/JiraIssueUpdateBuilderTest.java, src/test/java/hudson/plugins/jira/JiraIssueUpdaterTest.java, src/test/java/hudson/plugins/jira/JiraReleaseVersionUpdateBuilderTest.java, src/test/java/hudson/plugins/jira/JiraVersionCreatorBuilderTest.java, src/test/java/hudson/plugins/jira/pipeline/IssueFieldUpdateStepTest.java
https://github.com/jenkinsci/jenkins/pull/4829/
[JENKINS-46175](https://issues.jenkins.io/browse/JENKINS-46175)
Remove requirement for a workspace in all SimpleBuildSteps
We do not use the workspace at all in any of our steps so this allows us to remove the requirement. This also allows the steps to be used outside of a `node` block
=> Remove workspace requirement for SimpleBuildSteps

src/test/java/hudson/plugins/jira/JiraEnvironmentVariableBuilderTest.java
Fixes https://github.com/jenkinsci/jira-plugin/pull/733#issuecomment-3191423308
None. Rely on `ci.jenkins.io`.
=> Fix JUnit5 migration
